
package by.epam.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "SoapPriceService", targetNamespace = "http://example/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface SoapPriceService {


    /**
     * @param arg0
     * @return returns by.epam.soapclient.Price
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPriceByID", targetNamespace = "http://example/", className = "by.epam.soapclient.GetPriceByID")
    @ResponseWrapper(localName = "getPriceByIDResponse", targetNamespace = "http://example/", className = "by.epam.soapclient.GetPriceByIDResponse")
    @Action(input = "http://example/SoapPriceService/getPriceByIDRequest", output = "http://example/SoapPriceService/getPriceByIDResponse")
    public Price getPriceByID(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

}
