
package by.epam.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "SoapPriceService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:9000/SoapPrice?wsdl")
public class SoapPriceService_Service
        extends Service {

    private final static URL SOAPPRICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPRICESERVICE_EXCEPTION;
    private final static QName SOAPPRICESERVICE_QNAME = new QName("http://example/", "SoapPriceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/SoapPrice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPRICESERVICE_WSDL_LOCATION = url;
        SOAPPRICESERVICE_EXCEPTION = e;
    }

    public SoapPriceService_Service() {
        super(__getWsdlLocation(), SOAPPRICESERVICE_QNAME);
    }

    public SoapPriceService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPRICESERVICE_QNAME, features);
    }

    public SoapPriceService_Service(URL wsdlLocation) {
        super(wsdlLocation, SOAPPRICESERVICE_QNAME);
    }

    public SoapPriceService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPRICESERVICE_QNAME, features);
    }

    public SoapPriceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPriceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns SoapPriceService
     */
    @WebEndpoint(name = "SoapPriceServicePort")
    public SoapPriceService getSoapPriceServicePort() {
        return super.getPort(new QName("http://example/", "SoapPriceServicePort"), SoapPriceService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SoapPriceService
     */
    @WebEndpoint(name = "SoapPriceServicePort")
    public SoapPriceService getSoapPriceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "SoapPriceServicePort"), SoapPriceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPRICESERVICE_EXCEPTION != null) {
            throw SOAPPRICESERVICE_EXCEPTION;
        }
        return SOAPPRICESERVICE_WSDL_LOCATION;
    }

}
